In [13]:
from mxnet import autograd, nd

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\ProgramData\Anaconda3\lib\site-packages\h5py\tests\old\test_attrs_data.py:251: DeprecationWarning: invalid escape sequence \H
  s = b"Hello\x00\Hello"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\func_inspect.py:53: DeprecationWarning: invalid escape sequence \<
  '\<doctest (.*\.rst)\[(.*)\]\>', source_file).groups()
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\_memory_helpers.py:10: DeprecationWarning: invalid escape sequence \s
  cookie_re = re.compile("coding[:=]\s*([-\w.]+)")


In [18]:
with autograd.record():
    

In [19]:
y.backward()

In [21]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [37]:
class AutoGrad:
    def __init__(self, x, net):
        '''
        - 为了求有关变量 `x` 的梯度，我们需要先调用 `attach_grad` 函数来申请存储梯度所需要的内存。
        - 为了减少计算和内存开销，默认条件下 MXNet 不会记录用于求梯度的计算。
            我们需要调用 `record` 函数来要求 MXNet 记录与求梯度有关的计算
        - 通过调用 `backward` 函数自动求梯度
        '''
        x.attach_grad()
        with autograd.record():
            y = net(x)
        y.backward()
        self.grad = x.grad

In [38]:
x = nd.arange(4).reshape((4, 1))

def net(x):
    return 2 * nd.dot(x.T, x)

In [39]:
A = AutoGrad(x, net)
A.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>