In [1]:
import tables as tb
import numpy as np

载入我的一个自定义数据库, 详细介绍见: [Bunch 转换为 HDF5 文件：高效存储 Cifar 等数据集](https://www.cnblogs.com/q735613050/p/9244223.html)

In [2]:
h5 = tb.open_file('E:/xdata/X.h5')   

In [3]:
cifar = h5.root.cifar10    # 获取 cifar10 数据集

In [4]:
label_names = np.asanyarray(cifar.label_names, dtype='U')
print(label_names)   # 打印类别名字

['airplane' 'automobile' 'bird' 'cat' 'deer' 'dog' 'frog' 'horse' 'ship'
 'truck']


In [5]:
print(np.unique(cifar.testY))   # 验证类别数是否符合
print(np.unique(cifar.trainY))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


- `np.unique` 的作用是: 去除重复元素. 符合要求.
- `np.bincount` 对整数数组的元素计数.

In [6]:
print(np.bincount(cifar.testY))
print(np.bincount(cifar.trainY)) 

[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
[5000 5000 5000 5000 5000 5000 5000 5000 5000 5000]


从结果可以看出, `cifar10` 数据集是均衡的.

In [17]:
X_train = np.asanyarray(cifar.trainX, dtype=np.float).reshape((-1, 32*32*3))
X_test = np.asanyarray(cifar.testX, dtype=np.float).reshape((-1, 32*32*3))

In [18]:
from sklearn.preprocessing import StandardScaler

# 标准化处理
sc = StandardScaler()  
sc.fit(X_train)   # 计算数据中的每个特征的样本均值和标准差
X_train_std = sc.transform(X_train)   # 使用样本均值和标准差做标准化处理
X_test_std = sc.transform(X_test)